import { ethers } from "hardhat";
import dayjs from "dayjs";
import * as dotenv from "dotenv";
dotenv.config();

import { SupplyChain, SupplyChain__factory } from "../../typechain-types";
import { Result } from "@ethersproject/abi";
import { BigNumberish, ContractTransaction, ContractReceipt, BigNumber, Event } from "ethers";
import { PromiseOrValue, TypedEvent } from "../../typechain-types/common";

const connectContract = async (): Promise<SupplyChain> => {
  // Get the contract address
  const address: string | any = process.env.CONTRACT_ADDRESS;

  // Get the contract factory
  const SupplyChainFactory = await ethers.getContractFactory("SupplyChain");

  // Connect the contract on the blockchain
  const supplyChain: SupplyChain = SupplyChainFactory.attach(address);

  return supplyChain;
};

const main = async () => {
  // Connect the contract on the blockchain
  const supplyChain: SupplyChain = await connectContract();

  const boxSample: SupplyChain.BoxStruct[] = [
    {
      boxId: "0",
      productId: "1",
      quantity: "100",
      weight: "70",
      value: "1500",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "2",
      quantity: "200",
      weight: "150",
      value: "700",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "3",
      quantity: "300",
      weight: "200",
      value: "400",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "4",
      quantity: "400",
      weight: "300",
      value: "1000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "5",
      quantity: "500",
      weight: "400",
      value: "1500",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "6",
      quantity: "600",
      weight: "250",
      value: "5000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "7",
      quantity: "300",
      weight: "50",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "8",
      quantity: "400",
      weight: "40",
      value: "4000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "9",
      quantity: "200",
      weight: "20",
      value: "2000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "10",
      quantity: "1000",
      weight: "500",
      value: "15000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "11",
      quantity: "600",
      weight: "200",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "12",
      quantity: "500",
      weight: "100",
      value: "7000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "13",
      quantity: "400",
      weight: "70",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "14",
      quantity: "700",
      weight: "50",
      value: "5000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "15",
      quantity: "600",
      weight: "90",
      value: "8400",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "16",
      quantity: "500",
      weight: "150",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "17",
      quantity: "300",
      weight: "80",
      value: "4000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "18",
      quantity: "300",
      weight: "80",
      value: "4000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-01-21",
      expirationDate: "2024-01-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "1",
      quantity: "100",
      weight: "70",
      value: "1500",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "2",
      quantity: "200",
      weight: "150",
      value: "700",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "3",
      quantity: "300",
      weight: "200",
      value: "400",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "4",
      quantity: "400",
      weight: "300",
      value: "1000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "5",
      quantity: "500",
      weight: "400",
      value: "1500",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "6",
      quantity: "600",
      weight: "250",
      value: "5000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "7",
      quantity: "300",
      weight: "50",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "8",
      quantity: "400",
      weight: "40",
      value: "4000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "9",
      quantity: "200",
      weight: "20",
      value: "2000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "10",
      quantity: "1000",
      weight: "500",
      value: "15000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "11",
      quantity: "600",
      weight: "200",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "12",
      quantity: "500",
      weight: "100",
      value: "7000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "13",
      quantity: "400",
      weight: "70",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "14",
      quantity: "700",
      weight: "50",
      value: "5000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "15",
      quantity: "600",
      weight: "90",
      value: "8400",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "16",
      quantity: "500",
      weight: "150",
      value: "3000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "17",
      quantity: "300",
      weight: "80",
      value: "4000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
    {
      boxId: "0",
      productId: "18",
      quantity: "300",
      weight: "80",
      value: "4000",
      status: "0",
      isCompliance: true,
      productionDate: "2023-02-21",
      expirationDate: "2024-02-21",
      supplier: "Supplier A",
      supermarket: "NA",
      location: "Pending to store",
      lastUpdate: "0",
    },
  ];

  // Create the box
  console.log("Creating the box...");

  boxSample.forEach(async (box) => {
    // Run createProduct function then return the transaction details
    const tx: ContractTransaction = await supplyChain.createBox(box);

    // Wait the transaction to be mined and confirmed on the blockchain
    const txReceipt = await tx.wait();

    console.log(txReceipt);
  });

  console.log("Finished");
};

main();
