import { LocalizationProvider } from "@/components/@mui/x-date-pickers";
import { AdapterDayjs } from "@/components/@mui/x-date-pickers/AdapterDayjs";
import "@/styles/globals.css";

export const metadata = {
  title: "Supply Chain - Admin Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <LocalizationProvider dateAdapter={AdapterDayjs}>{children}</LocalizationProvider>
      </body>
    </html>
  );
}
